export const userActionsTypes = {
    FETCH_USER_INFO_SUCCESS: "FETCH_USER_INFO_SUCCESS",
    FETCH_USER_INFO_FAILURE: "FETCH_USER_INFO_FAILURE"
};

export const followActionsTypes = {
    FETCH_FOLLOWERS_SUCCESS: "FETCH_FOLLOWERS_SUCCESS",
    FETCH_FOLLOWERS_FAILURE: "FETCH_FOLLOWERS_FAILURE",
};

export const repoActionTypes = {
    FETCH_REPOS_SUCCESS: " FETCH_REPOS_SUCCESS",
    FETCH_REPOS_FAIL: "FETCH_REPOS_FAIL"
}